---
# tasks file for roles/loadbalancers
- name: Creating template
  template:
    src: ../files/lb-config.j2
    dest: /etc/httpd/conf.d/lb.conf
    owner: bin
    group: wheel
    mode: 064
  notify: restart apache
